### ISSUE TITLE
Error! can't create out file

### ISSUE THREAD

**Issue by twseptian** [mateuszk87/PcapViz#1]
great tool.thank you so much for develop this.
i got error 

$ python main.py -i smallFlows.pcap -o small_tcp_l2.png --layer3
WARNING: No route found for IPv6 destination :: (no default route?)
WARNING:root:could not load GeoIP data
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    g.draw(filename=args.out)
  File "/home/twster/PcapViz/pcapviz/core.py", line 116, in draw
    graph = self.get_graphviz_format()
  File "/home/twster/PcapViz/pcapviz/core.py", line 144, in get_graphviz_format
    agraph = networkx.to_agraph(self.graph)
AttributeError: 'module' object has no attribute 'to_agraph'
twster@hckndev:~/PcapViz$

**Comment by bakalon** [comment]
I'm also having the same issue. Any insight on how to fix this issue?

Edit: I got this to work by replacing line 144 with:  
agraph = networkx.drawing.nx_agraph.to_agraph(self.graph)

Works great now!
