### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by DarkCodacon** [mateuszk87/PcapViz#10]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from pcapviz.core import GraphManager
  File "/home/lau/PcapViz/pcapviz/core.py", line 8, in <module>
    from pygeoip import GeoIP
ImportError: No module named pygeoip

is there any chance that someone can take my pcap file and produce a layer2 and layer3 topology png in the meantime. I really need it at the moment.

**Comment by 1ultimat3** [comment]
try first:

pip install -r requirements.txt
