### ISSUE TITLE
Requirements not installing correctly

### ISSUE THREAD

**Issue by DarkCodacon** [mateuszk87/PcapViz#11]
When I try to install the requirements using the requirements.txt file I get the following errors:

![image](https://user-images.githubusercontent.com/45711737/49698321-28b15800-fbba-11e8-9b2a-effe37b88ab3.png)

Failed building wheel for pygraphpviz

**Comment by 1ultimat3** [comment]
you need to install graphviz first:

`apt-get install graphviz libgraphviz-dev `
