### ISSUE TITLE
Installing the requirement of graphviz

### ISSUE THREAD

**Issue by DarkCodacon** [mateuszk87/PcapViz#12]
When I am trying to install it, using the graphviz I can this issue:

![trying brooooooooooooooooooo](https://user-images.githubusercontent.com/45711737/49859119-ae1d4e00-fdee-11e8-8066-aa9e94dbee28.JPG)

**Comment by 1ultimat3** [comment]
Everything is fine, it works for you. Check your tester.png file.

With respect to the warning:
Please read the README with respect to the GeoIP data, which is optional.
