### ISSUE TITLE
GeoIP.dat is not available anymore

### ISSUE THREAD

**Issue by tbarbette** [mateuszk87/PcapViz#13]
Provider has moved to GeoLite2. Would it be possible to update? I'd like to check out your tool ;)

**Comment by codecat007** [comment]
wget sjolzy.cn/php/GeoIP/bak/GeoIP.dat.gz

**Comment by codecat007** [comment]
> Provider has moved to GeoLite2. Would it be possible to update? I'd like to check out your tool ;)

wget sjolzy.cn/php/GeoIP/bak/GeoIP.dat.gz

**Comment by greg-norton** [comment]
I was able to use Wayback Machine (archive.org) to find a version of GeoIP.dat.gz that worked.

Here's a snapshot from October of 2014:

https://web.archive.org/web/20141006081348/http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz

I just searched for a snapshot of this URL:
http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz

**Comment by fubar2** [comment]
In case anyone cares, I just created a pull request to use the new free maxmind python API available using
> pip3 install maxminddb

and db file obtained with

> wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz 

Working code at my fork https://github.com/fubar2/PcapViz

**Comment by fubar2** [comment]
That pull request is now merged. README describes how to download and install and requirements.txt includes the Maxmind db python API.

**Comment by 1ultimat3** [comment]
thanks @fubar2 for implementing this feature in #15
