### ISSUE TITLE
TypeError: 'errors' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by haha5566** [mateuszk87/PcapViz#3]
I install PcapViz on my ubuntu 14.04 
When I run the tset script `python main.py -i smallFlows.pcap -o small_tcp.png --layer3`
it returns 
`Traceback (most recent call last):`
`  File "main.py", line 3, in <module>`
`    from pcapviz.core import GraphManager`
`  File "/home/lin/PcapViz/pcapviz/__init__.py", line 1, in <module>`
`    from scapy.all import *`
`  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>`
`    from .config import *`
`  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>`
`    from .data import *`
`  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>`
`    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")`
`  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services`
`    f=open(filename, errors='ignore')`
`TypeError: 'errors' is an invalid keyword argument for this function`
How can i solve this? Thanks

**Comment by haha5566** [comment]
I change the requirements.txt
from
`scapy-python3`
to
`scapy`
and reinstall scapy

**Comment by 1ultimat3** [comment]
thanks! I have added your description in README

**Comment by Khandelwal-123** [comment]
I am also getting same error but the proposed solution doesn't worked for me. 
Any Suggestions?
