### ISSUE TITLE
FQDN & DNS Resolution

### ISSUE THREAD

**Issue by gbiagomba** [mateuszk87/PcapViz#4]
Hello,

This is not an "issue" more of a request and question. But I was wondering if the tool supported DNS resolution for IPs or if the tool can provide the FQDN of the IP address? If not, what modifications would I need to do to make it do so? Or would you mind making the modification to enable this feature? Either way it would be greatly appreciated!

**Comment by 1ultimat3** [comment]
That would be a great feature. The straightforward way (excluding virtual hosts) would be using reverse IP lookups (e.g. using DNSPython). Then you would need to overwrite the "label" in the draw function: https://github.com/mateuszk87/PcapViz/blob/master/pcapviz/core.py#L115

**Comment by 1ultimat3** [comment]
I will put that feature on my TODO list  👍

**Comment by gbiagomba** [comment]
Thank you sir!

**Comment by fubar2** [comment]
Cached reverse DNS lookup is working using socket.getfqdn() in my fork now along with CL parameters giving more control over the graph layout engine (dot gives very wide images - sfdn gives a more compact square layout) and node shape. I'll submit a pull request after a bit more testing.

**Comment by 1ultimat3** [comment]
big thanks @fubar2 for implementing this feature in #15
