### ISSUE TITLE
the lib 'networkx' has been updated

### ISSUE THREAD

**Issue by 33swordsman** [mateuszk87/PcapViz#5]
The lib 'networkx' has been updated to ver 2.0 in Sep, 2017(https://pypi.python.org/pypi/networkx/), which the version to download use 'pip install'. And the parameters of some functions have changed. For example the parameters of add_edges() in DiGraph have changed to 'def add_edge(self, u, v, **attr)' from 'def add_edge(self, u, v, attr_dict=None, **attr)'. So when I compile the source code, some errors occur like 'TypeError: add_edge() takes exactly 3 arguments (4 given)'.

**Comment by BenjaminHae** [comment]
Workaround is to reinstall the old version of networkx:
```
pip uninstall networkx
pip install networkx==1.11
```

**Comment by vjhebbar** [comment]
I got the same error after reverting to 1.11, installing the 1.41 RC1 version of pygraphviz fixed the problem

**Comment by bf-ckiendl** [comment]
After downgrading from networkx 2.1 to 1.11, I get
```
WARNING: PacketNGReader: Unparsed block type 5/#5
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pygeoip/util.py", line 37, in ip2long
    return int(binascii.hexlify(socket.inet_aton(ip)), 16)
OSError: illegal IP address string passed to inet_aton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PcapViz/main.py", line 35, in <module>
    g = GraphManager(packets, layer=layer)
  File "/root/PcapViz/pcapviz/core.py", line 45, in __init__
    self._retrieve_node_info(node)
  File "/root/PcapViz/pcapviz/core.py", line 75, in _retrieve_node_info
    country = self.geo_ip.country_name_by_addr(node_ip)
  File "/usr/local/lib/python3.4/dist-packages/pygeoip/__init__.py", line 488, in country_name_by_addr
    country_id = self.id_by_addr(addr)
  File "/usr/local/lib/python3.4/dist-packages/pygeoip/__init__.py", line 421, in id_by_addr
    ipnum = util.ip2long(addr)
  File "/usr/local/lib/python3.4/dist-packages/pygeoip/util.py", line 39, in ip2long
    return int(binascii.hexlify(socket.inet_pton(socket.AF_INET6, ip)), 16)
OSError: illegal IP address string passed to inet_pton
```

Installing pygraphviz 1.41 RC1 (`pip3 install --upgrade git+https://github.com/pygraphviz/pygraphviz.git#egg=pygraphviz`), as suggested above, does not work either, independent of the networkx-version used.

(iow, the software is currently not functional for me)

**Comment by 1ultimat3** [comment]
fixed
