### ISSUE TITLE
Error in core.py on line 42

### ISSUE THREAD

**Issue by Freeben666** [mateuszk87/PcapViz#6]
Hi,

I'm trying to use this python script (on Windows).

Commande line : 
> python .\main.py -i "input.pcap" -o "output.png" --layer2

Error:
> Traceback (most recent call last):
>   File ".\main.py", line 35, in <module>
>     g = GraphManager(packets, layer=layer)
>   File "P:\Python\PcapViz\pcapviz\core.py", line 42, in __init__
>     self.graph.add_edge(src, dst, {'packets': [packet]})
> TypeError: add_edge() takes 3 positional arguments but 4 were given

**Comment by Freeben666** [comment]
Same result on Linux (Ubuntu server 16.04 / Python 3.5.2)

**Comment by Ketup** [comment]
[https://github.com/mateuszk87/PcapViz/issues/5#issuecomment-344850382](url) resolves this issue.

**Comment by kerneltraceroute** [comment]
fixed url 404 error of upper comment

[resolves this issue-workaround](https://github.com/mateuszk87/PcapViz/issues/5#issuecomment-344850382)

**Comment by 1ultimat3** [comment]
upgrade to networkx 2 fixes this issue
