### ISSUE TITLE
graph is too large

### ISSUE THREAD

**Issue by jvlavl** [mateuszk87/PcapViz#9]
Hello,

great tool you have written.
Can you tell me how to solve the following issue?
RuntimeWarning: neato: graph is too large for cairo-renderer bitmaps. Scaling by 0.198021 to fit
warnings.warn(b"".join(errors).decode(self.encoding), RuntimeWarning)

Thanks in advance

John

**Comment by 1ultimat3** [comment]
Hi, thanks. Probably you shouldn't generate a bitmap file but rather a svg.

So try something like:
`python main.py --layer4  -i some.pcap -o some.svg`
